### ISSUE TITLE
Suricata and ntop PF_RING: IPS mode doesn't work

### ISSUE THREAD

**Issue by rdpmc** [ntop/PF_RING#100]
Hello
Why suricata in  --pfring mode  can't block packet, so only works in IDS mode, not in IPS.
Is it possible to run suricata in IPS mode with ntop pfring ?
I built pfring module and userland (without binary libraries in "libs" dir) and suricata supports pfring and run well. But it only alerts on drop rule (wDrop), not drop.
Thanks.

**Comment by cardigliano** [comment]
Hi
PF_RING IPS support in suricata is available at https://github.com/cardigliano/suricata/tree/dev-pfring but never merged mainstream
in essence this is the IPS patch https://github.com/cardigliano/suricata/commit/0df4ed10daf3fc2612f09a55b9a8d6f98f6b8f64 , at the very bottom you can see the suricata.yaml.in with the configuration example.

Alfredo

**Comment by rdpmc** [comment]
Thanks. I've tried it, using ping, and it is not blocks it (wDrop).

My config part concerning pf-ring:

pfring:
- interface: default
  
  cluster-id: 1
  
  cluster-type: cluster_flow
- interface: ethernet0
  
  copy-iface: ethernet2
  
  copy-mode: ips
- interface: ethernet2
  
  copy-iface: ethernet0
  
  copy-mode: ips

runmode: workers

In log thereis all ok ,some info from log:

PF_RING IPS activeted on eth0-->eth2
Enabling zero-copy for eth0
PF_RING IPS activeted on eth2-->eth0
Enabling zero-copy for eth2

And in alert log: only wDrop, while my rule has "drop" action. And ping is going through eth2-eth0

**Comment by cardigliano** [comment]
In essence inline mode is working now and forwarding packets, but the problem is that it does not drop packets, correct? Are you sure this is related to pf_ring? Did you try the same ocnfiguration with af_packet or other modules?

Alfredo

**Comment by Onotoko** [comment]
Hello you guys,
I tried with run suricata and pfring in IPS mode, but it cannot forward packet. Any body can help me?
```
pfring:
  - interface: eth2
    cluster-id: 99
    cluster-type: cluster_flow
    copy-iface: eth1
    copy-mode: ips
    checksum-checks: yes
  # Second interface
  - interface: eth1
    cluster-id: 98
    copy-iface: eth2
    copy-mode: ips
    cluster-type: cluster_flow
    checksum-checks: yes
```
Thanks!
