### ISSUE TITLE
ZC: missing packets

### ISSUE THREAD

**Issue by kirollosawad95** [ntop/PF_RING#883]
I  constantly get missing packets(bytes) when using `zc:`. I'm using `zcount` to validate. By printing out the length of the buffer.

```
    if(pfring_zc_recv_pkt(zq, &buffers[0], wait_for_packet) > 0) {
        printf("bytes recieved: %d\n",buffers[0]->len);
```
`sudo ./zcount -i zc:fiber10GB -g 1`
output:
```
bytes received: 3072
bytes received: 3072
bytes received: 3072
bytes received: 464 <- Missing bytes
bytes received: 3072
bytes received: 3072
bytes received: 3072
bytes received: 464 <- Missing bytes
```
No missing packets if I remove `zc:` from the interface.

I'm using ice module with E810, I compiled the kernel module and load it after adjusting `HUGEPAGES_NUM` to 10240
my throughput is 5.44Gbit/sec

pfring 8.4

**Comment by cardigliano** [comment]
Please provide cat /proc/net/pf_ring/dev/fiber10GB/info

**Comment by kirollosawad95** [comment]
```
Name:         fiber10GB
Index:        18
Address:      50:7C:6F:3C:0C:66
Polling Mode: NAPI/ZC
Promisc:      Disabled
Type:         Ethernet
Family:       Intel ice
TX Queues:    1
RX Queues:    1
Num RX Slots: 4096
Num TX Slots: 4096
RX Slot Size: 3072
TX Slot Size: 3072
```

**Comment by cardigliano** [comment]
What is the MTU of this link?

**Comment by kirollosawad95** [comment]
9700

**Comment by kirollosawad95** [comment]
here is my netplan config
```
    fiber10GB:
        addresses: [169.254.128.1/16]
        dhcp4: false
        mtu: 9700
        optional: true
        match:
            macaddress: 50:7c:6f:3c:0c:66
        set-name: fiber10GB 
```
